### ISSUE TITLE
0x8007007E exception

### ISSUE THREAD

**Issue by AbdulG771** [inorton/slp-sharp#1]
Hey, 

I have the problem that in line:
var slp = new SlpClient(String.Empty);

The DLL "slp": The specified module was not found. (Exception of HRESULT: 0x8007007E) cannot be loaded.

Any idea?

**Comment by inorton** [comment]
Hiya, you'll need to install the libslp C library for this to work.  But its been so many years since I wrote this that it might not work with recent SLP

**Comment by AbdulG771** [comment]
To be honest - I have no idea what to do. And I find absolutely no alternative for it 😂 Sorry but very thanks - I know its already many years ago

**Comment by AbdulG771** [comment]
Especially this line makes problems:
            SlpError err = SlpNativeMethods.Open(slpLang, SlpBoolean.True, ref hSlp);

Can you please help @inorton - I really need it

**Comment by inorton** [comment]
You need to compile the OpenSLP library, I coded the library against 2.0 but it needs the .dll/.so file.  The exception you are seeing is because that library file is missing.

You can get it at http://www.openslp.org/download.html

**Comment by AbdulG771** [comment]
Thanks! After copying the slp.dll it works again
